// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvZsf6zgktRKevi05V3wlCYtFaxV0r2cA',
    appId: '1:954897568224:web:e8621dfa8b833ba537db85',
    messagingSenderId: '954897568224',
    projectId: 'tafweejhub-b8f42',
    authDomain: 'tafweejhub-b8f42.firebaseapp.com',
    storageBucket: 'tafweejhub-b8f42.firebasestorage.app',
    measurementId: 'G-WGCKP345GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP2B8wPa2aXe3ELaB1OMVHFZSBHw8sCVw',
    appId: '1:954897568224:android:5c913ee1a600537037db85',
    messagingSenderId: '954897568224',
    projectId: 'tafweejhub-b8f42',
    storageBucket: 'tafweejhub-b8f42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwXZ7QRAbREF-EH3CyUWo7QAlz2l-dtco',
    appId: '1:954897568224:ios:bc7b8497f5a1e43837db85',
    messagingSenderId: '954897568224',
    projectId: 'tafweejhub-b8f42',
    storageBucket: 'tafweejhub-b8f42.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwXZ7QRAbREF-EH3CyUWo7QAlz2l-dtco',
    appId: '1:954897568224:ios:bc7b8497f5a1e43837db85',
    messagingSenderId: '954897568224',
    projectId: 'tafweejhub-b8f42',
    storageBucket: 'tafweejhub-b8f42.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvZsf6zgktRKevi05V3wlCYtFaxV0r2cA',
    appId: '1:954897568224:web:5c7bfa81fe7dcf9437db85',
    messagingSenderId: '954897568224',
    projectId: 'tafweejhub-b8f42',
    authDomain: 'tafweejhub-b8f42.firebaseapp.com',
    storageBucket: 'tafweejhub-b8f42.firebasestorage.app',
    measurementId: 'G-P81BBWEEK7',
  );

}